version: '3'

services:
  krisha:
    container_name: "krisha"
    build:
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 1000M
    expose:
      - 1337
    ports:
      - 1337:1337


